config/routes.rb
Rails.application.routes.draw do

  resources :cards, except: [:index, :show]
  resources :decks, except: [:index]
  resources :users, except: [:index]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/:id/forward' => 'tests#forward'
  get '/:id/backward' => 'tests#backward'
  post '/:id/forward' => 'tests#fvalidate'
  post '/:id/backward' => 'tests#bvalidate'

  root 'welcome#index'

end

app/models/user.rb
require 'active_record'
require 'bcrypt'

require_relative 'deck'

class User < ActiveRecord::Base
  include BCrypt

  has_many :decks, dependent: :destroy
  validates :name, :email, :password, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2 }

  # Modify for nil password hash
  def password
    @password ||= Password.new(password_hash) if password_hash
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions"><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<div class='container'>
<br>
<%= render 'form' %>
<br>
<br>
</div>

<span class='glyphicon glyphicon-chevron-left'></span> <%= link_to 'Back', :back %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<div class='container'>
<br>
<%= render 'form' %>
<br>
<br>
</div>

<span class='glyphicon glyphicon-chevron-left'></span> <%= link_to 'Back', :back %>

app/views/users/show.html.erb
<% if notice and notice.include? 'success' %>
  <p id="notice"><span class='glyphicon glyphicon-check'></span> <%= notice %></p>
<% elsif notice %>
  <p id="notice"><span class='glyphicon glyphicon-alert'></span> <%= notice %></p>
<% end %>

<h1><%= @user.name %>'s Quizzes</h1>

<div class='container'>

<br>
<% if @user == current_user %>
  <%= link_to 'New Deck', new_deck_path, :class => "btn btn-default btn-md" %>
<% end %>

<br>
<br>

<% if @user.decks.length == 0 %>
  <p>You don't have any decks yet!</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-2">Name</th>
        <th class="col-sm-2">Test</th>
        <th class="col-sm-2">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @user.decks.each do |deck| %>
      <tr>
        <td><%= link_to deck.name, deck %></td>
        <td><span class='glyphicon glyphicon-forward'></span> <a href='/<%= deck.id %>/forward'>Forward</a> | <span class='glyphicon glyphicon-backward'></span> <a href='/<%= deck.id %>/backward'>Backward</a></td>
        <% if @user == current_user %>
          <td><span class='glyphicon glyphicon-edit'></span> <%= link_to 'Rename', edit_deck_path(deck) %> | <span class='glyphicon glyphicon-trash'></span> <%= link_to 'Delete', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><span class='glyphicon glyphicon-ban-circle'></span></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

</div>

<br>

<p>
<% if @user == current_user %>
  <%= link_to 'Edit Account', edit_user_path(@user) %> |
  <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</p>