config/routes.rb
Rails.application.routes.draw do

  resources :cards, except: [:index, :show]
  resources :decks, except: [:index]
  resources :users, except: [:index]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/:id/forward' => 'tests#forward'
  get '/:id/backward' => 'tests#backward'
  post '/:id/forward' => 'tests#fvalidate'
  post '/:id/backward' => 'tests#bvalidate'

  root 'welcome#index'

end

app/models/deck.rb
require 'active_record'

require_relative 'user'
require_relative 'card'

class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :name, presence: true
  # validates_uniqueness_of :name, scope: :user
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    session[:deck_id] = @deck.id
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)
    respond_to do |format|
      if @deck.save
        current_user.decks << @deck
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions"><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<div class='container'>
<br>
<%= render 'form' %>
<br>
<br>
</div>

<span class='glyphicon glyphicon-chevron-left'></span> <%= link_to 'Back', :back %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<div class='container'>
<br>
<%= render 'form' %>
<br>
<br>
</div>

<span class='glyphicon glyphicon-chevron-left'></span> <%= link_to 'Back', :back %>

app/views/decks/show.html.erb
<% if notice and notice.include? 'success' %>
  <p id="notice"><span class='glyphicon glyphicon-check'></span> <%= notice %></p>
<% elsif notice %>
  <p id="notice"><span class='glyphicon glyphicon-alert'></span> <%= notice %></p>
<% end %>

<h1>
  <%= @deck.name %>
</h1>

<div class='container'>

<br>
<% if @deck.user == current_user %>
  <%= link_to 'Add Card', new_card_path, :class => "btn btn-default btn-md" %>
<% end %>

<br>
<br>

<% if @deck.cards.length == 0 %>
  <p>No cards in this deck yet!</p>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-2">Prompt</th>
        <th class="col-sm-2">Answer</th>
        <th class="col-sm-2">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @deck.cards.each do |card| %>
      <tr>
        <td><%= card.question %></td>
        <td><%= card.answer %></td>
        <% if @deck.user == current_user %>
          <td><span class='glyphicon glyphicon-edit'></span> <%= link_to 'Edit', edit_card_path(card) %> | <span class='glyphicon glyphicon-trash'></span> <%= link_to 'Delete', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><span class='glyphicon glyphicon-ban-circle'></span></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<a href='/<%= @deck.id %>/forward' class='btn btn-default btn-md'>Test Forward</a>
<a href='/<%= @deck.id %>/backward' class='btn btn-default btn-md'>Test Backward</a>
<br>

</div>

<br>

<p>
<% if @deck.user == current_user %>
  <%= link_to 'Rename', edit_deck_path(@deck) %> |
  <%= link_to 'Delete', @deck, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', current_user %>
</p>